import { AnonimousModelDefinition, AnonymousAttributes, MergeModelConstructors } from './define';
import { Model } from './model';
export { collection, metadata, AnonymousModelConstructor, InferAttrs } from './define';
export * from './attrDef';
export * from './metatypes';
export { AttributesMixin, LinkedAttributes } from './model';
export { Model };
export declare function attributes<D extends AnonimousModelDefinition, B1 extends typeof Model, B2 extends typeof Model, B3 extends typeof Model>(b1: B1, b2: B2, b3: B3, attrDefs: D): MergeModelConstructors<MergeModelConstructors<MergeModelConstructors<B1, B2>, B3>, AnonymousAttributes<D>>;
export declare function attributes<D extends AnonimousModelDefinition, B1 extends typeof Model, B2 extends typeof Model>(b1: B1, b2: B2, attrDefs: D): MergeModelConstructors<MergeModelConstructors<B1, B2>, AnonymousAttributes<D>>;
export declare function attributes<D extends AnonimousModelDefinition, B1 extends typeof Model>(b1: B1, attrDefs: D): MergeModelConstructors<B1, AnonymousAttributes<D>>;
export declare function attributes<D extends AnonimousModelDefinition>(attrDefs: D): AnonymousAttributes<D>;
export declare function auto(value: any): PropertyDecorator;
export declare function auto(proto: object, attrName: string): void;
