import { Mixable as Class } from '@type-r/mixture';
import { Model } from './model';
export * from './collection';
export * from './io-tools';
export * from '@type-r/mixture';
export * from './model';
export * from './relations';
export * from './transactions';
export { Model as Record, Class };
export { Linked } from '@linked/value';
export declare const on: any, off: any, trigger: any, once: any, listenTo: any, stopListening: any, listenToOnce: any;
export declare function transaction<F extends Function>(method: F): F;
